name: Environments and theyre variables and secrets
on: workflow_dispatch
jobs:
  matrix_job:
    strategy:
      matrix:
        value: [ Production, Test ]
    runs-on: ubuntu-latest
    environment: ${{ matrix.value }}
    env:
      username: ${{ vars.USERNAME }}
    steps:
      - name: Echo out the environment variables
        run: echo "username from ${{matrix.value}} is $env.username"
      - name: Echo out secrets directly
        run: echo "Username from ${{matrix.value}} is  ${{ secrets.USERNAME }}"
