name: First Golang Workflow
on: [ workflow_dispatch ]
defaults:
  run:
    shell: bash
    working-directory: Golang/MyCode
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from the repo to the runner
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Format the code in preparation for testing
        run: make format
      - name: Output event details
        run: |
          #echo "${{ toJSON(github.event) }}"  # print shedloads of them
          #echo "${{ toJSON(github.event.requested_team.name) }}"
          #echo "${{ toJSON(github.event.action) }}"
          echo "${{ toJSON(github.event.name) }}"
