name: iam matrix example
on: workflow_dispatch
jobs:
  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Repo
        id: Clone
        uses: actions/checkout@v4

      - name: Run Some Commands
        id: Commands
        run: echo $(ls -l)

      - name: Run some commands
        run: |
          echo "Clone outcome: ${{steps.Clone.outcome}}"
          echo "Clone status: ${{steps.Clone.status}}"
          echo "ls -l outcome: ${{steps.Commands.outcome}}"
          echo "ls -l status: ${{steps.Commands.status}}"

