name: IAM Role and Policy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  HelloWorld:
    if: inputs.Action == 'plan' && inputs.Environment == 'Production'
    runs-on: ubuntu-latest
    steps:
      - name: Print out inputs
        run: echo "Running Hello World"
