name: IAM Role and Policy
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'releases/**'
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  HelloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Print out inputs
        run: echo "Running Hello World"
