name: env variables example
on: workflow_dispatch
env:
  dog: "Bowzer the Dog"
jobs:
  dog_job:                        
    runs-on: ubuntu-latest
    env:                           
      greeting: "Woofy Woofy There" 
    steps:
      - name: "First Dog Step"
        run: echo "${{ env.greeting }} Your Pet is ${{ env.dog }}!"
