name: First Golang Workflow
on: [ workflow_dispatch ]
defaults:
  run:
    shell: bash
    working-directory: Golang/MyCode
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from the repo to the runner
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Format the code in preparation for testing
        run: make format
      - name: Run the Tests on functions in the Code
        run: make test
      - name: Run the binary 
        run: make run
      - name: Clean up and begone
        run: make rm
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download code from the repo to the runner
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Format code
        run: make format
      - name: Buld and run the Binary
        run: |
          make build
          make run_binary
      - name: Mock Deployment of the code
        run: echo "Deploying code Not..."
      - name: Clean up and be gone
        run: make rm
