name: iam matrix example
on: workflow_dispatch
jobs:
  setup_job:
    continue-on-error: true
    strategy: 
      matrix:
        environment: [ 650454640207, 191213556404 ]
        #environment: [dev , primary ]
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repo
        uses: actions/checkout@v4

      - name: Run some commands
        run: |
          if [ "${{ matrix.environment }}" == "191213556404" ]; then cd prod; else cd terraform ;fi
          echo $(pwd)
          echo "The environment is: ${{ matrix.environment }}"
          export role_arn="arn:aws:iam::"${{ matrix.environment }}":role/DevopsDroneRole"
          echo "The role arn is: $role_arn"

