name: jq example
on: workflow_dispatch
jobs:
  setup_job:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix_value }}
    steps:
      - name: Download the repo
        uses: actions/checkout@v3

      - name: Run the ls command to build up a slice of directories
        id: matrix
        run: echo "matrix_value=$(ls tools |jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT" 

      - name: Print Locally
        run: echo "${{ steps.matrix.outputs.matrix_value }}"


  display_output_job:
    runs-on: ubuntu-latest
    needs: [ setup_job ]
    env:
      matrix_var: ${{ fromJson(needs.create_output_job.outputs.matrix) }}
    steps:
      - name: print out environment variable
        run: echo "Directory is ${{ env.matrix_var }}"

