name: simple_output_workflow
on: workflow_dispatch
jobs:
  create_output:
    runs-on: ubuntu-latest
    outputs:
      random_output_variable: ${{ steps.random_step.random-number }}
    steps:
      - name: Generate a random number to use as output
        id: random_step
        run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      - name: Using the random-number generated in this job
        run: echo "The value of the random number is ${{ steps.random_step.outputs.random-number }}"
      - name: access the random number within the flow
        run: echo "The random number is ${{ outputs.random_output_variable }}"

  use_output:
    needs: create_output
    runs-on: ubuntu-latest
    env:
      create_output_var: ${{ needs.create_output.random_output_variable  }}
    steps:
      - name: first cut echo variable
        run: echo "Variable carried over ${{create_output_var}}"
      - name: second cut echo variable directly
        run: echo "Variable carried over ${{ needs.create_output.random_output_variable  }}"

