name: First Golang Workflow
on: [ workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from the repo to the runner
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Format the code in preparation for testing
        run: |
          cd Golang
          make format
      - name: Event Conditional
        run: |
          echo "$RUNNER_OS"
          echo "$env"
