name: env variables example
on: workflow_dispatch
env:
  dog: "Bowzer the Dog"
jobs:
  dog_job:                        
    runs-on: ubuntu-latest
    env:                           
      greeting: "Woofy Woofy There" 
    steps:
      - name: "Define a step specific environment variable"
        env:
          owner: "First Dog Owner"
      - name: "First Dog Step"
        run: echo "${{ env.greeting }} Owner is ${{env.owner}} Your Pet is ${{ env.dog }}!"
