name: Dickaround with Outputs
on: workflow_dispatch
jobs:
  create_output_job:
    runs-on: ubuntu-latest
    env:
      first_env_var: ${{ needs.create_output_job.outputs.first_var}}
    # Map a step output to a job output
    outputs:
      first_var: ${{ steps.first_step.outputs.first_var }} # steps and output are reserved words
    steps:
      - id: first_step                                        # handle used to dig down into the variable
        run: echo "first_var=hello world" >> "$GITHUB_OUTPUT" # dumps string into the output variable called hello_var

      - name: output value generated
        run: echo "Value is ${{steps.first_step.outputs.first_var}}"

  display_output_job:
    runs-on: ubuntu-latest
    needs: create_output_job  # must run after that job to get the output variable
    env:
      env_var: ${{needs.create_output_job.outputs.first_var}}
    steps:
      - name: echo out the environment variabl
        run: echo "Environment variable is ${{env.env_var}}"
