name: matrix example
on: workflow_dispatch
jobs:
  setup_job:
    continue-on-error: true
    strategy: 
      matrix:
        environment: [ prod, terraform ]
    defaults:
      run:
        working-directory: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Download the Repo
        uses: actions/checkout@v4
      - name: cd into the correct directory and run ls to confirm your in it
        run: |
          echo "The environment is: ${{ matrix.environment }}"
          echo $(pwd)
          echo $(ls)

