name: Environments and theyre variables and secrets
on: workflow_dispatch
jobs:
  test_job:                        
    runs-on: ubuntu-latest
    environment: Test
    env:
      username: ${{ vars.USERNAME }}
      password: ${{ secrets.PASSWORD }}
    steps:
      - name: Echo out the environment variables
        run: echo "username $env.username, password $env.password"
      - name: Echo out secrets directly
        run: echo "Name ${{ secrets.USERNAME }} password ${{ vars.PASSWORD }}"

  prod_job:
    runs-on: ubuntu-latest
    environment: Production
    env:
      username: ${{ vars.USERNAME }}
      password: ${{ secrets.PASSWORD }}
    steps:
      - name: Echo out the environment variables
        run: echo "username $env.username, password $env.password"
      - name: Echo out secrets directly
        run: echo "Name ${{ secrets.USERNAME }} password ${{ vars.PASSWORD }}"

