name: iam matrix example
on: workflow_dispatch
jobs:
  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Repo
        id: Clone
        uses: actions/checkout@v4

      - name: Run Some Commands
        id: Commands
        run: echo $(ls -l)

      - name: Run some commands
        run: |
          outcomeEmoji() { case "$1" in 'success') echo '✅';; 'failure') echo '❌';; *) echo '❓';; esac; }
          echo "Clone outcome: ${{steps.Clone.outcome}} - $(outcomeEmoji '${{ steps.Clone.outcome }}') Clone Step"
          echo "ls -l outcome: ${{steps.Commands.outcome}} - $(outcomeEmoji '${{ steps.Commands.outcome }}') Command Step"
