name: First Golang Workflow
on: [ workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Do some pwd and moving around
        run: |
          pwd
          cd Golang
          pwd
          cd
          pwd
          PATH=$(path)
          echo $PATH
      - name: Event Conditional
        run: |
          echo "$RUNNER_OS"
          echo "PATH: $GITHUB_PATH"
          echo "Runner user is: $RUNNER_USER"
