name: Play with variables

on: workflow_dispatch

env:
  dog: "Bowzer the Dog"
  cat: "Lottie the Kat"

jobs:
  dog_job:
    runs-on: ubuntu-latest
    env:
      greeting: "Woof Woof Doggy"
    steps:
      - name: The first Dog Step
        run: echo "${{env.greeting}} the pet is ${{env.dog}} with the owner ${{env.owner}}"
        env:
          owner: "Donald Duck"
