name: First Golang Workflow
on: [ workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from the repo to the runner
        uses: actions/checkout@v3 
      - name: Do some pwd and moving around
        run: |
          PWD=$(pwd)
          echo "Current Directory: $PWD"
          cd Golang
          echo $PATH
          PWD=$(pwd)
          echo "Current Directory: $PWD"
          cd
          PWD=$(pwd)
          echo "Current Directory: $PWD"

      - name: Event Conditional
        run: |
          echo "$RUNNER_OS"
          echo "PATH: $GITHUB_PATH"
          echo "Runner user is: $RUNNER_USER"
