name: Grabbing output from a find command run within the repo and capturing it to a variable then passing it down the chain
on: workflow_dispatch
jobs:
  create_output_job:
    runs-on: ubuntu-latest
    outputs:
      output_var: ${{ steps.test_file_step.outputs.find_var }}
    steps:
      - name: Download the Golang repo
        uses: actions/checkout@v3

      - name: Run the find command and grab list of outputs
        id: test_file_step
        run: find Maths/*_test.go -type f -execdir echo 'find_var={}'  >> $GITHUB_OUTPUT ';' 

      - name: Print the find variable locally
        run: echo "${{steps.test_file_step.outputs.find_var}}"
