name: Environment Variable Demonstration
on: workflow_dispatch
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      var_IAM: "arn:aws:iam::969296761654:role/IAMRole"
    steps:
      - name: Assume the appropriate IAM Role
        run: |
          echo "Role is ${{ env.var_IAM }}"
