name: Repository Secrets Demoe
on: workflow_dispatch
jobs:
  dog_job:                        
    runs-on: ubuntu-latest
    env:
      mongodb_username: ${{ vars.MONGODB_USERNAME }}
      mongodb_password: ${{ vars.MONGODB_PASSWORD }}
    steps:
      - name: Echo out the environment variables
        run: echo "username $env.mongodb_username, password $env.mongodb_password"
