name: env variables example
on: workflow_dispatch
env:
  dog: "Bowzer the Dog"
jobs:
  dog_job:
    run_on: ubuntu-latest
    env:
      greeting: "Woof Woof Doggy"
    steps:
      - name: Set environment local to the steps
        env:
          owner: "Local step dog owner"
      - name: First Dog Step
        run: echo "Local greeting: ${{env.greeting}}"

